cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductSitemap
from .views import about_page

sitemaps = {
    'products': ProductSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('about/', about_page, name='about_page'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.product_search, name='product_search'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250,
                            db_index=True)
    slug = models.SlugField(max_length=250,
                            unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=150,
                               blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'manufacturer'
        verbose_name_plural = 'manufacturers'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    guarantee = models.CharField(max_length=15,
                                 default='12 months')
    manufacturer = models.ForeignKey(Manufacturer,
                                     related_name='products',
                                     on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Review(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='reviews')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Review by {self.name} on {self.product}'

shop/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'email', 'body')
        widgets = {
            'body': forms.Textarea(attrs={'rows': 3}),
        }

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from .forms import ReviewForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    object_list = Product.objects.filter(available=True)
    # products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)

    paginator = Paginator(object_list, 9)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'page': page,
                   'products': products,
                   'cart_product_form': cart_product_form})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    reviews = product.reviews.filter(active=True)
    new_review = None

    if request.method == 'POST':
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            new_review = review_form.save(commit=False)
            new_review.product = product
            new_review.save()
    else:
        review_form = ReviewForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'reviews': reviews,
                   'new_review': new_review,
                   'review_form': review_form,
                   'cart_product_form': cart_product_form})

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}About page{% endblock %}

{% block content %}
    <h2>About Us </h2>
    <p>Here will be some information about our company.</p>
    <br>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Online store of batteries and chargers{% endblock %}</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
</head>
<body>
 <style>
     body {background-image: url("static/img/background-img.jpg");}
 </style>
 <div class="container-xl">
  <nav class="nav" style="background-color: #e3ebec">
      <ul class="nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'about_page' %}">About Company</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Delivery</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Payment</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Discounts and promotions</a>
          </li>
      </ul>
  </nav>
 </div>
  <div class="container-xl">
  <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:product_list' %}"><h3>Online store of batteries and chargers</h3></a>
              </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'search:product_search'%}" method="get">
              <input name = "query" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                  <svg class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                      <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                  </svg>Search</button>
          </form>
          <div id="cart">
              {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                      Your cart:
                      <a href="{% url "cart:cart_detail" %}" class="badge badge-primary">
                      {{ total_items }} item{{ total_items|pluralize }},
                      {{ cart.get_total_price }} BYN
                      </a>
                  {% else %}
                      Your cart is empty.
                  {% endif %}
              {% endwith %}
          </div>
      </div>
  </nav>
  </div>

  <div id="content" class="container-xl">
      {% block content %}
      {% endblock %}
  </div>

  <div class="container-xl" id="footer" style="background-color: #e3ebec">
      <p>Here will be some usefull information.</p>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
         integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
         crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>